## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [ ]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [3]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
df = pd.read_csv('/Users/irenemilanez/dataProjects/hw-explore-df/bridge-inspections-excerpt.csv')

df

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [4]:
## call the first 10 rows
df.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [5]:
## call the last 5 rows
df.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [6]:
## call a 20 random rows
df.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
29880,48,89,'DRAW',29533500.0,96354195.0,2.0,9.0,2001.0,3,19.0,N,N,N,7,6,NaN
9263,48,439,'MARINE CREEK',32481724.0,97215116.0,4.0,19.0,1960.0,4,2.0,5,6,7,7,N,NaN
8989,48,439,'TRIB ASH CREEK',32531257.0,97324530.0,4.0,19.0,1946.0,1,19.0,N,N,N,6,6,NaN
66676,48,85,'US 75 SBFR',33092923.0,96384509.0,NaN,12.0,2011.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
82062,51,117,'LITTLE BLUESTONE CREEK',36463517.0,78291228.0,1.0,7.0,1957.0,1,19.0,N,N,N,4,6,NaN
8653,48,439,'INTERNATIONAL PKWY',32514360.0,97022316.0,25.0,19.0,1974.0,4,2.0,6,7,7,N,N,NaN
77549,51,9,'Harris Creek',37262009.0,79090262.0,1.0,17.0,1967.0,3,2.0,6,5,6,7,N,NaN
76946,51,13,'ROUTE I-66',38525311.0,77071876.0,1.0,16.0,1981.0,4,2.0,6,6,6,N,N,NaN
90220,51,83,'Polecat Creek',36464248.0,79041209.0,1.0,9.0,2018.0,1,1.0,8,8,8,7,N,NaN
7296,48,439,'WESTERN CENTER BLVD',32514068.0,97185332.0,1.0,11.0,2001.0,5,2.0,7,7,7,N,N,NaN
92185,51,165,'RTE 340 @ ELKTON',38241851.0,78370872.0,NaN,6.0,1971.0,3,2.0,NaN,NaN,NaN,NaN,NaN,NaN
50293,48,257,'BACHELOR CREEK REL',32392602.0,96164729.0,2.0,9.0,1982.0,3,2.0,6,6,5,6,N,NaN
55773,48,479,'JABONCILLO CREEK BRANCH',28063398.0,99244255.0,2.0,9.0,2008.0,1,19.0,N,N,N,6,7,NaN
83905,51,167,'LEWIS CREEK',37004911.0,81580809.0,1.0,6.0,1948.0,4,2.0,6,6,5,6,N,NaN
40586,48,249,'PAISANO CREEK',27194734.0,98073793.0,1.0,2.0,1985.0,1,19.0,N,N,N,8,7,NaN
28697,48,339,'OUTFALL L',30140748.0,95284268.0,1.0,6.0,2010.0,1,19.0,N,N,N,6,7,NaN
33700,48,453,'BARTON CREEK',30144045.0,97480814.0,1.0,14.0,1969.0,5,2.0,6,7,7,6,N,NaN
10486,48,337,'EAST CAMPBELL CREEK',33532943.0,97312241.0,1.0,8.0,1995.0,1,19.0,N,N,N,7,7,NaN
65675,48,29,'N ST MARYS ST',29271706.0,98285446.0,NaN,19.0,1976.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
46023,48,113,'Lawther Dr',32512607.0,96430400.0,1.0,14.0,1959.0,5,2.0,6,6,7,N,N,NaN

In [7]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

PIER_PROTECTION_111

In [8]:
## call the top 7 rows
df.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [9]:
## call a sample of 10
df.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
9560,48,497,'BU 380 F',33135214.0,97354134.0,1.0,14.0,1996.0,5,5.0,7,7,7,N,N,NaN
14283,48,267,'DRAW',30205145.0,99352282.0,1.0,1.0,1967.0,1,19.0,N,N,N,7,6,NaN
17340,48,27,'METHEGLIN CRK #110',31140615.0,97302414.0,2.0,9.0,1940.0,1,1.0,6,6,6,6,N,NaN
58249,48,229,'DRAW',31090618.0,105163939.0,1.0,1.0,1965.0,2,1.0,6,6,7,7,N,NaN
99090,53,77,'AHTANUM CREEK N. FORK',46325400.0,120572400.0,2.0,8.0,1953.0,7,2.0,4,4,4,7,N,NaN
3787,48,181,'SH 56',33392195.0,96561490.0,1.0,2.0,1970.0,5,2.0,8,7,7,N,N,NaN
6267,48,251,'W BUFFALO CREEK',32204224.0,97231442.0,4.0,19.0,1929.0,1,4.0,6,6,5,5,N,NaN
69516,48,141,'AIRPORT RD NB',31493180.0,106241814.0,NaN,16.0,2008.0,5,1.0,NaN,NaN,NaN,NaN,NaN,NaN
26876,48,201,'SEALS GULLY',30025170.0,95274345.0,2.0,19.0,1977.0,5,0.0,6,7,7,8,N,NaN
34130,48,453,'COLLIER CREEK',30292151.0,97553817.0,1.0,6.0,1940.0,1,19.0,N,N,N,7,6,NaN

In [10]:
## call the bottom 6
df.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [11]:
## call the year built column using dot notation
df.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [14]:
## call FEATURES_DESC_006A as a series using square bracket notation

df["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [15]:
## what are the unique owner codes?
df["OWNER_022"].unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

According to Federal Highway Administration guidelines, these codes mean represent the type of agency that has primary responsibility for maintaining the structure.